export interface CityRegion {
  id: string;
  name: string;
  provinceId: string;
  provinceName: string;
}

export const CITY_REGIONS: CityRegion[] = [
  { id: "1107", name: "Kab. Aceh Barat", provinceId: "1100", provinceName: "Nanggroe Aceh Darussalam" },
  { id: "1112", name: "Kab. Aceh Barat Daya", provinceId: "1100", provinceName: "Nanggroe Aceh Darussalam" },
  { id: "1108", name: "Kab. Aceh Besar", provinceId: "1100", provinceName: "Nanggroe Aceh Darussalam" },
  { id: "1116", name: "Kab. Aceh Jaya", provinceId: "1100", provinceName: "Nanggroe Aceh Darussalam" },
  { id: "1103", name: "Kab. Aceh Selatan", provinceId: "1100", provinceName: "Nanggroe Aceh Darussalam" },
  { id: "1102", name: "Kab. Aceh Singkil", provinceId: "1100", provinceName: "Nanggroe Aceh Darussalam" },
  { id: "1114", name: "Kab. Aceh Tamiang", provinceId: "1100", provinceName: "Nanggroe Aceh Darussalam" },
  { id: "1106", name: "Kab. Aceh Tengah", provinceId: "1100", provinceName: "Nanggroe Aceh Darussalam" },
  { id: "1104", name: "Kab. Aceh Tenggara", provinceId: "1100", provinceName: "Nanggroe Aceh Darussalam" },
  { id: "1105", name: "Kab. Aceh Timur", provinceId: "1100", provinceName: "Nanggroe Aceh Darussalam" },
  { id: "1111", name: "Kab. Aceh Utara", provinceId: "1100", provinceName: "Nanggroe Aceh Darussalam" },
  { id: "3101", name: "Kab. Adm. Kepulauan Seribu", provinceId: "3100", provinceName: "DKI Jakarta" },
  { id: "1307", name: "Kab. Agam", provinceId: "1300", provinceName: "Sumatera Barat" },
  { id: "5307", name: "Kab. Alor", provinceId: "5300", provinceName: "Nusa Tenggara Timur" },
  { id: "1208", name: "Kab. Asahan", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "9415", name: "Kab. Asmat", provinceId: "9400", provinceName: "Papua" },
  { id: "5103", name: "Kab. Badung", provinceId: "5100", provinceName: "Bali" },
  { id: "6311", name: "Kab. Balangan", provinceId: "6300", provinceName: "Kalimantan Selatan" },
  { id: "3204", name: "Kab. Bandung", provinceId: "3200", provinceName: "Jawa Barat" },
  { id: "3217", name: "Kab. Bandung Barat", provinceId: "3200", provinceName: "Jawa Barat" },
  { id: "7202", name: "Kab. Banggai", provinceId: "7200", provinceName: "Sulawesi Tengah" },
  { id: "7201", name: "Kab. Banggai Kepulauan", provinceId: "7200", provinceName: "Sulawesi Tengah" },
  { id: "7211", name: "Kab. Banggai Laut", provinceId: "7200", provinceName: "Sulawesi Tengah" },
  { id: "1901", name: "Kab. Bangka", provinceId: "1900", provinceName: "Kep. Bangka Belitung" },
  { id: "1903", name: "Kab. Bangka Barat", provinceId: "1900", provinceName: "Kep. Bangka Belitung" },
  { id: "1905", name: "Kab. Bangka Selatan", provinceId: "1900", provinceName: "Kep. Bangka Belitung" },
  { id: "1904", name: "Kab. Bangka Tengah", provinceId: "1900", provinceName: "Kep. Bangka Belitung" },
  { id: "3526", name: "Kab. Bangkalan", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "5106", name: "Kab. Bangli", provinceId: "5100", provinceName: "Bali" },
  { id: "6303", name: "Kab. Banjar", provinceId: "6300", provinceName: "Kalimantan Selatan" },
  { id: "3304", name: "Kab. Banjarnegara", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "7303", name: "Kab. Bantaeng", provinceId: "7300", provinceName: "Sulawesi Selatan" },
  { id: "3402", name: "Kab. Bantul", provinceId: "3400", provinceName: "DI Yogyakarta" },
  { id: "1607", name: "Kab. Banyuasin", provinceId: "1600", provinceName: "Sumatera Selatan" },
  { id: "3302", name: "Kab. Banyumas", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "3510", name: "Kab. Banyuwangi", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "6304", name: "Kab. Barito Kuala", provinceId: "6300", provinceName: "Kalimantan Selatan" },
  { id: "6204", name: "Kab. Barito Selatan", provinceId: "6200", provinceName: "Kalimantan Tengah" },
  { id: "6212", name: "Kab. Barito Timur", provinceId: "6200", provinceName: "Kalimantan Tengah" },
  { id: "6205", name: "Kab. Barito Utara", provinceId: "6200", provinceName: "Kalimantan Tengah" },
  { id: "7310", name: "Kab. Barru", provinceId: "7300", provinceName: "Sulawesi Selatan" },
  { id: "3325", name: "Kab. Batang", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "1504", name: "Kab. Batang Hari", provinceId: "1500", provinceName: "Jambi" },
  { id: "1219", name: "Kab. Batu Bara", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "3216", name: "Kab. Bekasi", provinceId: "3200", provinceName: "Jawa Barat" },
  { id: "1902", name: "Kab. Belitung", provinceId: "1900", provinceName: "Kep. Bangka Belitung" },
  { id: "1906", name: "Kab. Belitung Timur", provinceId: "1900", provinceName: "Kep. Bangka Belitung" },
  { id: "5306", name: "Kab. Belu", provinceId: "5300", provinceName: "Nusa Tenggara Timur" },
  { id: "1117", name: "Kab. Bener Meriah", provinceId: "1100", provinceName: "Nanggroe Aceh Darussalam" },
  { id: "1408", name: "Kab. Bengkalis", provinceId: "1400", provinceName: "Riau" },
  { id: "6102", name: "Kab. Bengkayang", provinceId: "6100", provinceName: "Kalimantan Barat" },
  { id: "1701", name: "Kab. Bengkulu Selatan", provinceId: "1700", provinceName: "Bengkulu" },
  { id: "1709", name: "Kab. Bengkulu Tengah", provinceId: "1700", provinceName: "Bengkulu" },
  { id: "1703", name: "Kab. Bengkulu Utara", provinceId: "1700", provinceName: "Bengkulu" },
  { id: "6405", name: "Kab. Berau", provinceId: "6400", provinceName: "Kalimantan Timur" },
  { id: "9409", name: "Kab. Biak Numfor", provinceId: "9400", provinceName: "Papua" },
  { id: "5206", name: "Kab. Bima", provinceId: "5200", provinceName: "Nusa Tenggara Barat" },
  { id: "2102", name: "Kab. Bintan", provinceId: "2100", provinceName: "Kepulauan Riau" },
  { id: "1110", name: "Kab. Bireuen", provinceId: "1100", provinceName: "Nanggroe Aceh Darussalam" },
  { id: "3505", name: "Kab. Blitar", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "3316", name: "Kab. Blora", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "7501", name: "Kab. Boalemo", provinceId: "7500", provinceName: "Gorontalo" },
  { id: "3201", name: "Kab. Bogor", provinceId: "3200", provinceName: "Jawa Barat" },
  { id: "3522", name: "Kab. Bojonegoro", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "7101", name: "Kab. Bolaang Mengondow", provinceId: "7100", provinceName: "Sulawesi Utara" },
  { id: "7110", name: "Kab. Bolaang Mongondow Selatan", provinceId: "7100", provinceName: "Sulawesi Utara" },
  { id: "7111", name: "Kab. Bolaang Mongondow Timur", provinceId: "7100", provinceName: "Sulawesi Utara" },
  { id: "7107", name: "Kab. Bolaang Mongondow Utara", provinceId: "7100", provinceName: "Sulawesi Utara" },
  { id: "7406", name: "Kab. Bombana", provinceId: "7400", provinceName: "Sulawesi Tenggara" },
  { id: "3511", name: "Kab. Bondowoso", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "7311", name: "Kab. Bone", provinceId: "7300", provinceName: "Sulawesi Selatan" },
  { id: "7504", name: "Kab. Bone Bolango", provinceId: "7500", provinceName: "Gorontalo" },
  { id: "9413", name: "Kab. Boven Digoel", provinceId: "9400", provinceName: "Papua" },
  { id: "3309", name: "Kab. Boyolali", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "3329", name: "Kab. Brebes", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "5108", name: "Kab. Buleleng", provinceId: "5100", provinceName: "Bali" },
  { id: "7302", name: "Kab. Bulukumba", provinceId: "7300", provinceName: "Sulawesi Selatan" },
  { id: "6502", name: "Kab. Bulungan", provinceId: "6500", provinceName: "Kalimantan Utara" },
  { id: "1509", name: "Kab. Bungo", provinceId: "1500", provinceName: "Jambi" },
  { id: "7207", name: "Kab. Buol", provinceId: "7200", provinceName: "Sulawesi Tengah" },
  { id: "8104", name: "Kab. Buru", provinceId: "8100", provinceName: "Maluku" },
  { id: "8109", name: "Kab. Buru Selatan", provinceId: "8100", provinceName: "Maluku" },
  { id: "7401", name: "Kab. Buton", provinceId: "7400", provinceName: "Sulawesi Tenggara" },
  { id: "7415", name: "Kab. Buton Selatan", provinceId: "7400", provinceName: "Sulawesi Tenggara" },
  { id: "7414", name: "Kab. Buton Tengah", provinceId: "7400", provinceName: "Sulawesi Tenggara" },
  { id: "7409", name: "Kab. Buton Utara", provinceId: "7400", provinceName: "Sulawesi Tenggara" },
  { id: "3207", name: "Kab. Ciamis", provinceId: "3200", provinceName: "Jawa Barat" },
  { id: "3203", name: "Kab. Cianjur", provinceId: "3200", provinceName: "Jawa Barat" },
  { id: "3301", name: "Kab. Cilacap", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "3209", name: "Kab. Cirebon", provinceId: "3200", provinceName: "Jawa Barat" },
  { id: "1210", name: "Kab. Dairi", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "9436", name: "Kab. Deiyai", provinceId: "9400", provinceName: "Papua" },
  { id: "1212", name: "Kab. Deli Serdang", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "3321", name: "Kab. Demak", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "1311", name: "Kab. Dharmasraya", provinceId: "1300", provinceName: "Sumatera Barat" },
  { id: "9434", name: "Kab. Dogiyai", provinceId: "9400", provinceName: "Papua" },
  { id: "5205", name: "Kab. Dompu", provinceId: "5200", provinceName: "Nusa Tenggara Barat" },
  { id: "7205", name: "Kab. Donggala", provinceId: "7200", provinceName: "Sulawesi Tengah" },
  { id: "1611", name: "Kab. Empat Lawang", provinceId: "1600", provinceName: "Sumatera Selatan" },
  { id: "5311", name: "Kab. Ende", provinceId: "5300", provinceName: "Nusa Tenggara Timur" },
  { id: "7316", name: "Kab. Enrekang", provinceId: "7300", provinceName: "Sulawesi Selatan" },
  { id: "9101", name: "Kab. Fak-Fak", provinceId: "9100", provinceName: "Papua Barat" },
  { id: "5309", name: "Kab. Flores Timur", provinceId: "5300", provinceName: "Nusa Tenggara Timur" },
  { id: "3205", name: "Kab. Garut", provinceId: "3200", provinceName: "Jawa Barat" },
  { id: "1113", name: "Kab. Gayo Lues", provinceId: "1100", provinceName: "Nanggroe Aceh Darussalam" },
  { id: "5104", name: "Kab. Gianyar", provinceId: "5100", provinceName: "Bali" },
  { id: "7502", name: "Kab. Gorontalo", provinceId: "7500", provinceName: "Gorontalo" },
  { id: "7505", name: "Kab. Gorontalo Utara", provinceId: "7500", provinceName: "Gorontalo" },
  { id: "7306", name: "Kab. Gowa", provinceId: "7300", provinceName: "Sulawesi Selatan" },
  { id: "3525", name: "Kab. Gresik", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "3315", name: "Kab. Grobogan", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "3403", name: "Kab. Gunung Kidul", provinceId: "3400", provinceName: "DI Yogyakarta" },
  { id: "6211", name: "Kab. Gunung Mas", provinceId: "6200", provinceName: "Kalimantan Tengah" },
  { id: "8202", name: "Kab. Halmahera Barat", provinceId: "8200", provinceName: "Maluku Utara" },
  { id: "8204", name: "Kab. Halmahera Selatan", provinceId: "8200", provinceName: "Maluku Utara" },
  { id: "8201", name: "Kab. Halmahera Tengah", provinceId: "8200", provinceName: "Maluku Utara" },
  { id: "8206", name: "Kab. Halmahera Timur", provinceId: "8200", provinceName: "Maluku Utara" },
  { id: "8205", name: "Kab. Halmahera Utara", provinceId: "8200", provinceName: "Maluku Utara" },
  { id: "6306", name: "Kab. Hulu Sungai Selatan", provinceId: "6300", provinceName: "Kalimantan Selatan" },
  { id: "6307", name: "Kab. Hulu Sungai Tengah", provinceId: "6300", provinceName: "Kalimantan Selatan" },
  { id: "6308", name: "Kab. Hulu Sungai Utara", provinceId: "6300", provinceName: "Kalimantan Selatan" },
  { id: "1215", name: "Kab. Humbang Hasundutan", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "1403", name: "Kab. Indragiri Hilir", provinceId: "1400", provinceName: "Riau" },
  { id: "1402", name: "Kab. Indragiri Hulu", provinceId: "1400", provinceName: "Riau" },
  { id: "3212", name: "Kab. Indramayu", provinceId: "3200", provinceName: "Jawa Barat" },
  { id: "9435", name: "Kab. Intan Jaya", provinceId: "9400", provinceName: "Papua" },
  { id: "9403", name: "Kab. Jayapura", provinceId: "9400", provinceName: "Papua" },
  { id: "9402", name: "Kab. Jayawijaya", provinceId: "9400", provinceName: "Papua" },
  { id: "3509", name: "Kab. Jember", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "5101", name: "Kab. Jembrana", provinceId: "5100", provinceName: "Bali" },
  { id: "7304", name: "Kab. Jeneponto", provinceId: "7300", provinceName: "Sulawesi Selatan" },
  { id: "3320", name: "Kab. Jepara", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "3517", name: "Kab. Jombang", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "9102", name: "Kab. Kaimana", provinceId: "9100", provinceName: "Papua Barat" },
  { id: "1406", name: "Kab. Kampar", provinceId: "1400", provinceName: "Riau" },
  { id: "6203", name: "Kab. Kapuas", provinceId: "6200", provinceName: "Kalimantan Tengah" },
  { id: "6108", name: "Kab. Kapuas Hulu", provinceId: "6100", provinceName: "Kalimantan Barat" },
  { id: "5107", name: "Kab. Karang Asem", provinceId: "5100", provinceName: "Bali" },
  { id: "3313", name: "Kab. Karanganyar", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "3215", name: "Kab. Karawang", provinceId: "3200", provinceName: "Jawa Barat" },
  { id: "2101", name: "Kab. Karimun", provinceId: "2100", provinceName: "Kepulauan Riau" },
  { id: "1211", name: "Kab. Karo", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "6209", name: "Kab. Katingan", provinceId: "6200", provinceName: "Kalimantan Tengah" },
  { id: "1704", name: "Kab. Kaur", provinceId: "1700", provinceName: "Bengkulu" },
  { id: "6111", name: "Kab. Kayong Utara", provinceId: "6100", provinceName: "Kalimantan Barat" },
  { id: "3305", name: "Kab. Kebumen", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "3506", name: "Kab. Kediri", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "9420", name: "Kab. Keerom", provinceId: "9400", provinceName: "Papua" },
  { id: "3324", name: "Kab. Kendal", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "1708", name: "Kab. Kepahiang", provinceId: "1700", provinceName: "Bengkulu" },
  { id: "2105", name: "Kab. Kepulauan Anambas", provinceId: "2100", provinceName: "Kepulauan Riau" },
  { id: "8105", name: "Kab. Kepulauan Aru", provinceId: "8100", provinceName: "Maluku" },
  { id: "1301", name: "Kab. Kepulauan Mentawai", provinceId: "1300", provinceName: "Sumatera Barat" },
  { id: "1410", name: "Kab. Kepulauan Meranti", provinceId: "1400", provinceName: "Riau" },
  { id: "7301", name: "Kab. Kepulauan Selayar", provinceId: "7300", provinceName: "Sulawesi Selatan" },
  { id: "7108", name: "Kab. Kepulauan Siau Tagulandang Biaro", provinceId: "7100", provinceName: "Sulawesi Utara" },
  { id: "8203", name: "Kab. Kepulauan Sula", provinceId: "8200", provinceName: "Maluku Utara" },
  { id: "7104", name: "Kab. Kepulauan Talaud", provinceId: "7100", provinceName: "Sulawesi Utara" },
  { id: "9408", name: "Kab. Kepulauan Yapen", provinceId: "9400", provinceName: "Papua" },
  { id: "1501", name: "Kab. Kerinci", provinceId: "1500", provinceName: "Jambi" },
  { id: "6106", name: "Kab. Ketapang", provinceId: "6100", provinceName: "Kalimantan Barat" },
  { id: "3310", name: "Kab. Klaten", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "5105", name: "Kab. Klungkung", provinceId: "5100", provinceName: "Bali" },
  { id: "7404", name: "Kab. Kolaka", provinceId: "7400", provinceName: "Sulawesi Tenggara" },
  { id: "7411", name: "Kab. Kolaka Timur", provinceId: "7400", provinceName: "Sulawesi Tenggara" },
  { id: "7408", name: "Kab. Kolaka Utara", provinceId: "7400", provinceName: "Sulawesi Tenggara" },
  { id: "7403", name: "Kab. Konawe", provinceId: "7400", provinceName: "Sulawesi Tenggara" },
  { id: "7412", name: "Kab. Konawe Kepulauan", provinceId: "7400", provinceName: "Sulawesi Tenggara" },
  { id: "7405", name: "Kab. Konawe Selatan", provinceId: "7400", provinceName: "Sulawesi Tenggara" },
  { id: "7410", name: "Kab. Konawe Utara", provinceId: "7400", provinceName: "Sulawesi Tenggara" },
  { id: "6302", name: "Kab. Kota Baru", provinceId: "6300", provinceName: "Kalimantan Selatan" },
  { id: "6201", name: "Kab. Kotawaringin Barat", provinceId: "6200", provinceName: "Kalimantan Tengah" },
  { id: "6202", name: "Kab. Kotawaringin Timur", provinceId: "6200", provinceName: "Kalimantan Tengah" },
  { id: "1401", name: "Kab. Kuantan Singingi", provinceId: "1400", provinceName: "Riau" },
  { id: "6112", name: "Kab. Kubu Raya", provinceId: "6100", provinceName: "Kalimantan Barat" },
  { id: "3319", name: "Kab. Kudus", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "3401", name: "Kab. Kulon Progo", provinceId: "3400", provinceName: "DI Yogyakarta" },
  { id: "3208", name: "Kab. Kuningan", provinceId: "3200", provinceName: "Jawa Barat" },
  { id: "5303", name: "Kab. Kupang", provinceId: "5300", provinceName: "Nusa Tenggara Timur" },
  { id: "6402", name: "Kab. Kutai Barat", provinceId: "6400", provinceName: "Kalimantan Timur" },
  { id: "6403", name: "Kab. Kutai Kertanegara", provinceId: "6400", provinceName: "Kalimantan Timur" },
  { id: "6404", name: "Kab. Kutai Timur", provinceId: "6400", provinceName: "Kalimantan Timur" },
  { id: "1207", name: "Kab. Labuhan Batu", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "1222", name: "Kab. Labuhanbatu Selatan", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "1223", name: "Kab. Labuhanbatu Utara", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "1604", name: "Kab. Lahat", provinceId: "1600", provinceName: "Sumatera Selatan" },
  { id: "6207", name: "Kab. Lamandau", provinceId: "6200", provinceName: "Kalimantan Tengah" },
  { id: "3524", name: "Kab. Lamongan", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "1801", name: "Kab. Lampung Barat", provinceId: "1800", provinceName: "Lampung" },
  { id: "1803", name: "Kab. Lampung Selatan", provinceId: "1800", provinceName: "Lampung" },
  { id: "1805", name: "Kab. Lampung Tengah", provinceId: "1800", provinceName: "Lampung" },
  { id: "1804", name: "Kab. Lampung Timur", provinceId: "1800", provinceName: "Lampung" },
  { id: "1806", name: "Kab. Lampung Utara", provinceId: "1800", provinceName: "Lampung" },
  { id: "6103", name: "Kab. Landak", provinceId: "6100", provinceName: "Kalimantan Barat" },
  { id: "1213", name: "Kab. Langkat", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "9430", name: "Kab. Lanny Jaya", provinceId: "9400", provinceName: "Papua" },
  { id: "3602", name: "Kab. Lebak", provinceId: "3600", provinceName: "Banten" },
  { id: "1707", name: "Kab. Lebong", provinceId: "1700", provinceName: "Bengkulu" },
  { id: "5308", name: "Kab. Lembata", provinceId: "5300", provinceName: "Nusa Tenggara Timur" },
  { id: "1308", name: "Kab. Lima Puluh Koto", provinceId: "1300", provinceName: "Sumatera Barat" },
  { id: "2104", name: "Kab. Lingga", provinceId: "2100", provinceName: "Kepulauan Riau" },
  { id: "5201", name: "Kab. Lombok Barat", provinceId: "5200", provinceName: "Nusa Tenggara Barat" },
  { id: "5202", name: "Kab. Lombok Tengah", provinceId: "5200", provinceName: "Nusa Tenggara Barat" },
  { id: "5203", name: "Kab. Lombok Timur", provinceId: "5200", provinceName: "Nusa Tenggara Barat" },
  { id: "5208", name: "Kab. Lombok Utara", provinceId: "5200", provinceName: "Nusa Tenggara Barat" },
  { id: "3508", name: "Kab. Lumajang", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "7317", name: "Kab. Luwu", provinceId: "7300", provinceName: "Sulawesi Selatan" },
  { id: "7325", name: "Kab. Luwu Timur", provinceId: "7300", provinceName: "Sulawesi Selatan" },
  { id: "7322", name: "Kab. Luwu Utara", provinceId: "7300", provinceName: "Sulawesi Selatan" },
  { id: "3519", name: "Kab. Madiun", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "3308", name: "Kab. Magelang", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "3520", name: "Kab. Magetan", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "6411", name: "Kab. Mahakam Ulu", provinceId: "6400", provinceName: "Kalimantan Timur" },
  { id: "3210", name: "Kab. Majalengka", provinceId: "3200", provinceName: "Jawa Barat" },
  { id: "7601", name: "Kab. Majene", provinceId: "7600", provinceName: "Sulawesi Barat" },
  { id: "5321", name: "Kab. Malaka", provinceId: "5300", provinceName: "Nusa Tenggara Timur" },
  { id: "3507", name: "Kab. Malang", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "6501", name: "Kab. Malinau", provinceId: "6500", provinceName: "Kalimantan Utara" },
  { id: "8108", name: "Kab. Maluku Barat Daya", provinceId: "8100", provinceName: "Maluku" },
  { id: "8103", name: "Kab. Maluku Tengah", provinceId: "8100", provinceName: "Maluku" },
  { id: "8102", name: "Kab. Maluku Tenggara", provinceId: "8100", provinceName: "Maluku" },
  { id: "8101", name: "Kab. Maluku Tenggara Barat", provinceId: "8100", provinceName: "Maluku" },
  { id: "7603", name: "Kab. Mamasa", provinceId: "7600", provinceName: "Sulawesi Barat" },
  { id: "9428", name: "Kab. Mamberamo Raya", provinceId: "9400", provinceName: "Papua" },
  { id: "9431", name: "Kab. Mamberamo Tengah", provinceId: "9400", provinceName: "Papua" },
  { id: "7604", name: "Kab. Mamuju", provinceId: "7600", provinceName: "Sulawesi Barat" },
  { id: "7606", name: "Kab. Mamuju Tengah", provinceId: "7600", provinceName: "Sulawesi Barat" },
  { id: "7605", name: "Kab. Mamuju Utara", provinceId: "7600", provinceName: "Sulawesi Barat" },
  { id: "1202", name: "Kab. Mandailing Natal", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "5313", name: "Kab. Manggarai", provinceId: "5300", provinceName: "Nusa Tenggara Timur" },
  { id: "5315", name: "Kab. Manggarai Barat", provinceId: "5300", provinceName: "Nusa Tenggara Timur" },
  { id: "5319", name: "Kab. Manggarai Timur", provinceId: "5300", provinceName: "Nusa Tenggara Timur" },
  { id: "9105", name: "Kab. Manokwari", provinceId: "9100", provinceName: "Papua Barat" },
  { id: "9111", name: "Kab. Manokwari Selatan", provinceId: "9100", provinceName: "Papua Barat" },
  { id: "9414", name: "Kab. Mappi", provinceId: "9400", provinceName: "Papua" },
  { id: "7308", name: "Kab. Maros", provinceId: "7300", provinceName: "Sulawesi Selatan" },
  { id: "9110", name: "Kab. Maybrat", provinceId: "9100", provinceName: "Papua Barat" },
  { id: "6110", name: "Kab. Melawi", provinceId: "6100", provinceName: "Kalimantan Barat" },
  { id: "6104", name: "Kab. Mempawah", provinceId: "6100", provinceName: "Kalimantan Barat" },
  { id: "1502", name: "Kab. Merangin", provinceId: "1500", provinceName: "Jambi" },
  { id: "9401", name: "Kab. Merauke", provinceId: "9400", provinceName: "Papua" },
  { id: "1811", name: "Kab. Mesuji", provinceId: "1800", provinceName: "Lampung" },
  { id: "9412", name: "Kab. Mimika", provinceId: "9400", provinceName: "Papua" },
  { id: "7102", name: "Kab. Minahasa", provinceId: "7100", provinceName: "Sulawesi Utara" },
  { id: "7105", name: "Kab. Minahasa Selatan", provinceId: "7100", provinceName: "Sulawesi Utara" },
  { id: "7109", name: "Kab. Minahasa Tenggara", provinceId: "7100", provinceName: "Sulawesi Utara" },
  { id: "7106", name: "Kab. Minahasa Utara", provinceId: "7100", provinceName: "Sulawesi Utara" },
  { id: "3516", name: "Kab. Mojokerto", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "7203", name: "Kab. Morowali", provinceId: "7200", provinceName: "Sulawesi Tengah" },
  { id: "7212", name: "Kab. Morowali Utara", provinceId: "7200", provinceName: "Sulawesi Tengah" },
  { id: "1603", name: "Kab. Muara Enim", provinceId: "1600", provinceName: "Sumatera Selatan" },
  { id: "1505", name: "Kab. Muaro Jambi", provinceId: "1500", provinceName: "Jambi" },
  { id: "1706", name: "Kab. Muko Muko", provinceId: "1700", provinceName: "Bengkulu" },
  { id: "7402", name: "Kab. Muna", provinceId: "7400", provinceName: "Sulawesi Tenggara" },
  { id: "7413", name: "Kab. Muna Barat", provinceId: "7400", provinceName: "Sulawesi Tenggara" },
  { id: "6213", name: "Kab. Murung Raya", provinceId: "6200", provinceName: "Kalimantan Tengah" },
  { id: "1606", name: "Kab. Musi Banyu Asin", provinceId: "1600", provinceName: "Sumatera Selatan" },
  { id: "1605", name: "Kab. Musi Rawas", provinceId: "1600", provinceName: "Sumatera Selatan" },
  { id: "1613", name: "Kab. Musi Rawas Utara", provinceId: "1600", provinceName: "Sumatera Selatan" },
  { id: "9404", name: "Kab. Nabire", provinceId: "9400", provinceName: "Papua" },
  { id: "1115", name: "Kab. Nagan Raya", provinceId: "1100", provinceName: "Nanggroe Aceh Darussalam" },
  { id: "5318", name: "Kab. Nagekeo", provinceId: "5300", provinceName: "Nusa Tenggara Timur" },
  { id: "2103", name: "Kab. Natuna", provinceId: "2100", provinceName: "Kepulauan Riau" },
  { id: "9429", name: "Kab. Nduga", provinceId: "9400", provinceName: "Papua" },
  { id: "5312", name: "Kab. Ngada", provinceId: "5300", provinceName: "Nusa Tenggara Timur" },
  { id: "3518", name: "Kab. Nganjuk", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "3521", name: "Kab. Ngawi", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "1201", name: "Kab. Nias", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "1225", name: "Kab. Nias Barat", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "1214", name: "Kab. Nias Selatan", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "1224", name: "Kab. Nias Utara", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "6503", name: "Kab. Nunukan", provinceId: "6500", provinceName: "Kalimantan Utara" },
  { id: "1610", name: "Kab. Ogan Ilir", provinceId: "1600", provinceName: "Sumatera Selatan" },
  { id: "1602", name: "Kab. Ogan Komering Ilir", provinceId: "1600", provinceName: "Sumatera Selatan" },
  { id: "1601", name: "Kab. Ogan Komering Ulu", provinceId: "1600", provinceName: "Sumatera Selatan" },
  { id: "1608", name: "Kab. Oku Selatan", provinceId: "1600", provinceName: "Sumatera Selatan" },
  { id: "1609", name: "Kab. Oku Timur", provinceId: "1600", provinceName: "Sumatera Selatan" },
  { id: "3501", name: "Kab. Pacitan", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "1221", name: "Kab. Padang Lawas", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "1220", name: "Kab. Padang Lawas Utara", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "1306", name: "Kab. Padang Pariaman", provinceId: "1300", provinceName: "Sumatera Barat" },
  { id: "7503", name: "Kab. Pahuwato", provinceId: "7500", provinceName: "Gorontalo" },
  { id: "1216", name: "Kab. Pakpak Bharat", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "3528", name: "Kab. Pamekasan", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "3601", name: "Kab. Pandeglang", provinceId: "3600", provinceName: "Banten" },
  { id: "3218", name: "Kab. Pangandaran", provinceId: "3200", provinceName: "Jawa Barat" },
  { id: "7309", name: "Kab. Pangkajene Kepulauan", provinceId: "7300", provinceName: "Sulawesi Selatan" },
  { id: "9410", name: "Kab. Paniai", provinceId: "9400", provinceName: "Papua" },
  { id: "7208", name: "Kab. Parigi Moutong", provinceId: "7200", provinceName: "Sulawesi Tengah" },
  { id: "1309", name: "Kab. Pasaman", provinceId: "1300", provinceName: "Sumatera Barat" },
  { id: "1312", name: "Kab. Pasaman Barat", provinceId: "1300", provinceName: "Sumatera Barat" },
  { id: "6401", name: "Kab. Paser", provinceId: "6400", provinceName: "Kalimantan Timur" },
  { id: "3514", name: "Kab. Pasuruan", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "3318", name: "Kab. Pati", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "9112", name: "Kab. Pegunungan Arfak", provinceId: "9100", provinceName: "Papua Barat" },
  { id: "9417", name: "Kab. Pegunungan Bintang", provinceId: "9400", provinceName: "Papua" },
  { id: "3326", name: "Kab. Pekalongan", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "1404", name: "Kab. Pelalawan", provinceId: "1400", provinceName: "Riau" },
  { id: "3327", name: "Kab. Pemalang", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "6409", name: "Kab. Penajam Paser Utara", provinceId: "6400", provinceName: "Kalimantan Timur" },
  { id: "1612", name: "Kab. Penukal Abab Lematang Ilir", provinceId: "1600", provinceName: "Sumatera Selatan" },
  { id: "1809", name: "Kab. Pesawaran", provinceId: "1800", provinceName: "Lampung" },
  { id: "1813", name: "Kab. Pesisir Barat", provinceId: "1800", provinceName: "Lampung" },
  { id: "1302", name: "Kab. Pesisir Selatan", provinceId: "1300", provinceName: "Sumatera Barat" },
  { id: "1109", name: "Kab. Pidie", provinceId: "1100", provinceName: "Nanggroe Aceh Darussalam" },
  { id: "1118", name: "Kab. Pidie Jaya", provinceId: "1100", provinceName: "Nanggroe Aceh Darussalam" },
  { id: "7315", name: "Kab. Pinrang", provinceId: "7300", provinceName: "Sulawesi Selatan" },
  { id: "7602", name: "Kab. Polewali Mandar", provinceId: "7600", provinceName: "Sulawesi Barat" },
  { id: "3502", name: "Kab. Ponorogo", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "7204", name: "Kab. Poso", provinceId: "7200", provinceName: "Sulawesi Tengah" },
  { id: "1810", name: "Kab. Pringsewu", provinceId: "1800", provinceName: "Lampung" },
  { id: "3513", name: "Kab. Probolinggo", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "6210", name: "Kab. Pulang Pisau", provinceId: "6200", provinceName: "Kalimantan Tengah" },
  { id: "8207", name: "Kab. Pulau Morotai", provinceId: "8200", provinceName: "Maluku Utara" },
  { id: "8208", name: "Kab. Pulau Taliabu", provinceId: "8200", provinceName: "Maluku Utara" },
  { id: "9433", name: "Kab. Puncak", provinceId: "9400", provinceName: "Papua" },
  { id: "9411", name: "Kab. Puncak Jaya", provinceId: "9400", provinceName: "Papua" },
  { id: "3303", name: "Kab. Purbalingga", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "3214", name: "Kab. Purwakarta", provinceId: "3200", provinceName: "Jawa Barat" },
  { id: "3306", name: "Kab. Purworejo", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "9108", name: "Kab. Raja Ampat", provinceId: "9100", provinceName: "Papua Barat" },
  { id: "1702", name: "Kab. Rejang Lebong", provinceId: "1700", provinceName: "Bengkulu" },
  { id: "3317", name: "Kab. Rembang", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "1409", name: "Kab. Rokan Hilir", provinceId: "1400", provinceName: "Riau" },
  { id: "1407", name: "Kab. Rokan Hulu", provinceId: "1400", provinceName: "Riau" },
  { id: "5314", name: "Kab. Rote Ndao", provinceId: "5300", provinceName: "Nusa Tenggara Timur" },
  { id: "5320", name: "Kab. Sabu Raijua", provinceId: "5300", provinceName: "Nusa Tenggara Timur" },
  { id: "6101", name: "Kab. Sambas", provinceId: "6100", provinceName: "Kalimantan Barat" },
  { id: "1217", name: "Kab. Samosir", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "3527", name: "Kab. Sampang", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "6105", name: "Kab. Sanggau", provinceId: "6100", provinceName: "Kalimantan Barat" },
  { id: "7103", name: "Kab. Sangihe", provinceId: "7100", provinceName: "Sulawesi Utara" },
  { id: "9419", name: "Kab. Sarmi", provinceId: "9400", provinceName: "Papua" },
  { id: "1503", name: "Kab. Sarolangun", provinceId: "1500", provinceName: "Jambi" },
  { id: "6109", name: "Kab. Sekadau", provinceId: "6100", provinceName: "Kalimantan Barat" },
  { id: "1705", name: "Kab. Seluma", provinceId: "1700", provinceName: "Bengkulu" },
  { id: "3322", name: "Kab. Semarang", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "8106", name: "Kab. Seram Bagian Barat", provinceId: "8100", provinceName: "Maluku" },
  { id: "8107", name: "Kab. Seram Bagian Timur", provinceId: "8100", provinceName: "Maluku" },
  { id: "3604", name: "Kab. Serang", provinceId: "3600", provinceName: "Banten" },
  { id: "1218", name: "Kab. Serdang Bedagai", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "6208", name: "Kab. Seruyan", provinceId: "6200", provinceName: "Kalimantan Tengah" },
  { id: "1405", name: "Kab. Siak", provinceId: "1400", provinceName: "Riau" },
  { id: "7314", name: "Kab. Sidenreng Rappang", provinceId: "7300", provinceName: "Sulawesi Selatan" },
  { id: "3515", name: "Kab. Sidoarjo", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "7210", name: "Kab. Sigi", provinceId: "7200", provinceName: "Sulawesi Tengah" },
  { id: "1304", name: "Kab. Sijunjung", provinceId: "1300", provinceName: "Sumatera Barat" },
  { id: "5310", name: "Kab. Sikka", provinceId: "5300", provinceName: "Nusa Tenggara Timur" },
  { id: "1209", name: "Kab. Simalungun", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "1101", name: "Kab. Simeulue", provinceId: "1100", provinceName: "Nanggroe Aceh Darussalam" },
  { id: "7307", name: "Kab. Sinjai", provinceId: "7300", provinceName: "Sulawesi Selatan" },
  { id: "6107", name: "Kab. Sintang", provinceId: "6100", provinceName: "Kalimantan Barat" },
  { id: "3512", name: "Kab. Situbondo", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "3404", name: "Kab. Sleman", provinceId: "3400", provinceName: "DI Yogyakarta" },
  { id: "1303", name: "Kab. Solok", provinceId: "1300", provinceName: "Sumatera Barat" },
  { id: "1310", name: "Kab. Solok Selatan", provinceId: "1300", provinceName: "Sumatera Barat" },
  { id: "7312", name: "Kab. Soppeng", provinceId: "7300", provinceName: "Sulawesi Selatan" },
  { id: "9107", name: "Kab. Sorong", provinceId: "9100", provinceName: "Papua Barat" },
  { id: "9106", name: "Kab. Sorong Selatan", provinceId: "9100", provinceName: "Papua Barat" },
  { id: "3314", name: "Kab. Sragen", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "3213", name: "Kab. Subang", provinceId: "3200", provinceName: "Jawa Barat" },
  { id: "3202", name: "Kab. Sukabumi", provinceId: "3200", provinceName: "Jawa Barat" },
  { id: "6206", name: "Kab. Sukamara", provinceId: "6200", provinceName: "Kalimantan Tengah" },
  { id: "3311", name: "Kab. Sukoharjo", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "5301", name: "Kab. Sumba Barat", provinceId: "5300", provinceName: "Nusa Tenggara Timur" },
  { id: "5317", name: "Kab. Sumba Barat Daya", provinceId: "5300", provinceName: "Nusa Tenggara Timur" },
  { id: "5316", name: "Kab. Sumba Tengah", provinceId: "5300", provinceName: "Nusa Tenggara Timur" },
  { id: "5302", name: "Kab. Sumba Timur", provinceId: "5300", provinceName: "Nusa Tenggara Timur" },
  { id: "5204", name: "Kab. Sumbawa", provinceId: "5200", provinceName: "Nusa Tenggara Barat" },
  { id: "5207", name: "Kab. Sumbawa Barat", provinceId: "5200", provinceName: "Nusa Tenggara Barat" },
  { id: "3211", name: "Kab. Sumedang", provinceId: "3200", provinceName: "Jawa Barat" },
  { id: "3529", name: "Kab. Sumenep", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "9427", name: "Kab. Supiori", provinceId: "9400", provinceName: "Papua" },
  { id: "6309", name: "Kab. Tabalong", provinceId: "6300", provinceName: "Kalimantan Selatan" },
  { id: "5102", name: "Kab. Tabanan", provinceId: "5100", provinceName: "Bali" },
  { id: "7305", name: "Kab. Takalar", provinceId: "7300", provinceName: "Sulawesi Selatan" },
  { id: "9109", name: "Kab. Tambrauw", provinceId: "9100", provinceName: "Papua Barat" },
  { id: "6504", name: "Kab. Tana Tidung", provinceId: "6500", provinceName: "Kalimantan Utara" },
  { id: "7318", name: "Kab. Tana Toraja", provinceId: "7300", provinceName: "Sulawesi Selatan" },
  { id: "6310", name: "Kab. Tanah Bumbu", provinceId: "6300", provinceName: "Kalimantan Selatan" },
  { id: "1305", name: "Kab. Tanah Datar", provinceId: "1300", provinceName: "Sumatera Barat" },
  { id: "6301", name: "Kab. Tanah Laut", provinceId: "6300", provinceName: "Kalimantan Selatan" },
  { id: "3603", name: "Kab. Tangerang", provinceId: "3600", provinceName: "Banten" },
  { id: "1802", name: "Kab. Tanggamus", provinceId: "1800", provinceName: "Lampung" },
  { id: "1507", name: "Kab. Tanjung Jabung Barat", provinceId: "1500", provinceName: "Jambi" },
  { id: "1506", name: "Kab. Tanjung Jabung Timur", provinceId: "1500", provinceName: "Jambi" },
  { id: "1203", name: "Kab. Tapanuli Selatan", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "1204", name: "Kab. Tapanuli Tengah", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "1205", name: "Kab. Tapanuli Utara", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "6305", name: "Kab. Tapin", provinceId: "6300", provinceName: "Kalimantan Selatan" },
  { id: "3206", name: "Kab. Tasikmalaya", provinceId: "3200", provinceName: "Jawa Barat" },
  { id: "1508", name: "Kab. Tebo", provinceId: "1500", provinceName: "Jambi" },
  { id: "3328", name: "Kab. Tegal", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "9104", name: "Kab. Teluk Bintuni", provinceId: "9100", provinceName: "Papua Barat" },
  { id: "9103", name: "Kab. Teluk Wondama", provinceId: "9100", provinceName: "Papua Barat" },
  { id: "3323", name: "Kab. Temanggung", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "5304", name: "Kab. Timor Tengah Selatan", provinceId: "5300", provinceName: "Nusa Tenggara Timur" },
  { id: "5305", name: "Kab. Timor Tengah Utara", provinceId: "5300", provinceName: "Nusa Tenggara Timur" },
  { id: "1206", name: "Kab. Toba Samosir", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "7209", name: "Kab. Tojo Una Una", provinceId: "7200", provinceName: "Sulawesi Tengah" },
  { id: "7206", name: "Kab. Toli-Toli", provinceId: "7200", provinceName: "Sulawesi Tengah" },
  { id: "9418", name: "Kab. Tolikara", provinceId: "9400", provinceName: "Papua" },
  { id: "7326", name: "Kab. Toraja Utara", provinceId: "7300", provinceName: "Sulawesi Selatan" },
  { id: "3503", name: "Kab. Trenggalek", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "3523", name: "Kab. Tuban", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "1808", name: "Kab. Tulang Bawang", provinceId: "1800", provinceName: "Lampung" },
  { id: "1812", name: "Kab. Tulang Bawang Barat", provinceId: "1800", provinceName: "Lampung" },
  { id: "3504", name: "Kab. Tulungagung", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "7313", name: "Kab. Wajo", provinceId: "7300", provinceName: "Sulawesi Selatan" },
  { id: "7407", name: "Kab. Wakatobi", provinceId: "7400", provinceName: "Sulawesi Tenggara" },
  { id: "9426", name: "Kab. Waropen", provinceId: "9400", provinceName: "Papua" },
  { id: "1807", name: "Kab. Way Kanan", provinceId: "1800", provinceName: "Lampung" },
  { id: "3312", name: "Kab. Wonogiri", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "3307", name: "Kab. Wonosobo", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "9416", name: "Kab. Yahukimo", provinceId: "9400", provinceName: "Papua" },
  { id: "9432", name: "Kab. Yalimo", provinceId: "9400", provinceName: "Papua" },
  { id: "8171", name: "Kota Ambon", provinceId: "8100", provinceName: "Maluku" },
  { id: "6471", name: "Kota Balikpapan", provinceId: "6400", provinceName: "Kalimantan Timur" },
  { id: "1171", name: "Kota Banda Aceh", provinceId: "1100", provinceName: "Nanggroe Aceh Darussalam" },
  { id: "1871", name: "Kota Bandar Lampung", provinceId: "1800", provinceName: "Lampung" },
  { id: "3273", name: "Kota Bandung", provinceId: "3200", provinceName: "Jawa Barat" },
  { id: "3279", name: "Kota Banjar", provinceId: "3200", provinceName: "Jawa Barat" },
  { id: "6372", name: "Kota Banjar Baru", provinceId: "6300", provinceName: "Kalimantan Selatan" },
  { id: "6371", name: "Kota Banjarmasin", provinceId: "6300", provinceName: "Kalimantan Selatan" },
  { id: "2171", name: "Kota Batam", provinceId: "2100", provinceName: "Kepulauan Riau" },
  { id: "3579", name: "Kota Batu", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "7472", name: "Kota Bau Bau", provinceId: "7400", provinceName: "Sulawesi Tenggara" },
  { id: "3275", name: "Kota Bekasi", provinceId: "3200", provinceName: "Jawa Barat" },
  { id: "1771", name: "Kota Bengkulu", provinceId: "1700", provinceName: "Bengkulu" },
  { id: "5272", name: "Kota Bima", provinceId: "5200", provinceName: "Nusa Tenggara Barat" },
  { id: "1276", name: "Kota Binjai", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "7172", name: "Kota Bitung", provinceId: "7100", provinceName: "Sulawesi Utara" },
  { id: "3572", name: "Kota Blitar", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "3271", name: "Kota Bogor", provinceId: "3200", provinceName: "Jawa Barat" },
  { id: "6474", name: "Kota Bontang", provinceId: "6400", provinceName: "Kalimantan Timur" },
  { id: "1375", name: "Kota Bukittinggi", provinceId: "1300", provinceName: "Sumatera Barat" },
  { id: "3672", name: "Kota Cilegon", provinceId: "3600", provinceName: "Banten" },
  { id: "3277", name: "Kota Cimahi", provinceId: "3200", provinceName: "Jawa Barat" },
  { id: "3274", name: "Kota Cirebon", provinceId: "3200", provinceName: "Jawa Barat" },
  { id: "5171", name: "Kota Denpasar", provinceId: "5100", provinceName: "Bali" },
  { id: "3276", name: "Kota Depok", provinceId: "3200", provinceName: "Jawa Barat" },
  { id: "1473", name: "Kota Dumai", provinceId: "1400", provinceName: "Riau" },
  { id: "7571", name: "Kota Gorontalo", provinceId: "7500", provinceName: "Gorontalo" },
  { id: "1278", name: "Kota Gunungsitoli", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "3174", name: "Kota Jakarta Barat", provinceId: "3100", provinceName: "DKI Jakarta" },
  { id: "3173", name: "Kota Jakarta Pusat", provinceId: "3100", provinceName: "DKI Jakarta" },
  { id: "3171", name: "Kota Jakarta Selatan", provinceId: "3100", provinceName: "DKI Jakarta" },
  { id: "3172", name: "Kota Jakarta Timur", provinceId: "3100", provinceName: "DKI Jakarta" },
  { id: "3175", name: "Kota Jakarta Utara", provinceId: "3100", provinceName: "DKI Jakarta" },
  { id: "1571", name: "Kota Jambi", provinceId: "1500", provinceName: "Jambi" },
  { id: "9471", name: "Kota Jayapura", provinceId: "9400", provinceName: "Papua" },
  { id: "3571", name: "Kota Kediri", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "7471", name: "Kota Kendari", provinceId: "7400", provinceName: "Sulawesi Tenggara" },
  { id: "7174", name: "Kota Kotamobagu", provinceId: "7100", provinceName: "Sulawesi Utara" },
  { id: "5371", name: "Kota Kupang", provinceId: "5300", provinceName: "Nusa Tenggara Timur" },
  { id: "1173", name: "Kota Langsa", provinceId: "1100", provinceName: "Nanggroe Aceh Darussalam" },
  { id: "1174", name: "Kota Lhokseumawe", provinceId: "1100", provinceName: "Nanggroe Aceh Darussalam" },
  { id: "1674", name: "Kota Lubuk Linggau", provinceId: "1600", provinceName: "Sumatera Selatan" },
  { id: "3577", name: "Kota Madiun", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "3371", name: "Kota Magelang", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "7371", name: "Kota Makassar", provinceId: "7300", provinceName: "Sulawesi Selatan" },
  { id: "3573", name: "Kota Malang", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "7171", name: "Kota Manado", provinceId: "7100", provinceName: "Sulawesi Utara" },
  { id: "5271", name: "Kota Mataram", provinceId: "5200", provinceName: "Nusa Tenggara Barat" },
  { id: "1275", name: "Kota Medan", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "1872", name: "Kota Metro", provinceId: "1800", provinceName: "Lampung" },
  { id: "3576", name: "Kota Mojokerto", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "1371", name: "Kota Padang", provinceId: "1300", provinceName: "Sumatera Barat" },
  { id: "1374", name: "Kota Padang Panjang", provinceId: "1300", provinceName: "Sumatera Barat" },
  { id: "1277", name: "Kota Padang Sidempuan", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "1673", name: "Kota Pagar Alam", provinceId: "1600", provinceName: "Sumatera Selatan" },
  { id: "6271", name: "Kota Palangka Raya", provinceId: "6200", provinceName: "Kalimantan Tengah" },
  { id: "1671", name: "Kota Palembang", provinceId: "1600", provinceName: "Sumatera Selatan" },
  { id: "7373", name: "Kota Palopo", provinceId: "7300", provinceName: "Sulawesi Selatan" },
  { id: "7271", name: "Kota Palu", provinceId: "7200", provinceName: "Sulawesi Tengah" },
  { id: "1971", name: "Kota Pangkal Pinang", provinceId: "1900", provinceName: "Kep. Bangka Belitung" },
  { id: "7372", name: "Kota Pare-Pare", provinceId: "7300", provinceName: "Sulawesi Selatan" },
  { id: "1377", name: "Kota Pariaman", provinceId: "1300", provinceName: "Sumatera Barat" },
  { id: "3575", name: "Kota Pasuruan", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "1376", name: "Kota Payakumbuh", provinceId: "1300", provinceName: "Sumatera Barat" },
  { id: "3375", name: "Kota Pekalongan", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "1471", name: "Kota Pekanbaru", provinceId: "1400", provinceName: "Riau" },
  { id: "1273", name: "Kota Pematang Siantar", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "6171", name: "Kota Pontianak", provinceId: "6100", provinceName: "Kalimantan Barat" },
  { id: "1672", name: "Kota Prabumulih", provinceId: "1600", provinceName: "Sumatera Selatan" },
  { id: "3574", name: "Kota Probolinggo", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "1172", name: "Kota Sabang", provinceId: "1100", provinceName: "Nanggroe Aceh Darussalam" },
  { id: "3373", name: "Kota Salatiga", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "6472", name: "Kota Samarinda", provinceId: "6400", provinceName: "Kalimantan Timur" },
  { id: "1373", name: "Kota Sawah Lunto", provinceId: "1300", provinceName: "Sumatera Barat" },
  { id: "3374", name: "Kota Semarang", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "3673", name: "Kota Serang", provinceId: "3600", provinceName: "Banten" },
  { id: "1271", name: "Kota Sibolga", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "6172", name: "Kota Singkawang", provinceId: "6100", provinceName: "Kalimantan Barat" },
  { id: "1372", name: "Kota Solok", provinceId: "1300", provinceName: "Sumatera Barat" },
  { id: "9171", name: "Kota Sorong", provinceId: "9100", provinceName: "Papua Barat" },
  { id: "1175", name: "Kota Subulussalam", provinceId: "1100", provinceName: "Nanggroe Aceh Darussalam" },
  { id: "3272", name: "Kota Sukabumi", provinceId: "3200", provinceName: "Jawa Barat" },
  { id: "1572", name: "Kota Sungai Penuh", provinceId: "1500", provinceName: "Jambi" },
  { id: "3578", name: "Kota Surabaya", provinceId: "3500", provinceName: "Jawa Timur" },
  { id: "3372", name: "Kota Surakarta", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "3671", name: "Kota Tangerang", provinceId: "3600", provinceName: "Banten" },
  { id: "3674", name: "Kota Tangerang Selatan", provinceId: "3600", provinceName: "Banten" },
  { id: "1272", name: "Kota Tanjung Balai", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "2172", name: "Kota Tanjung Pinang", provinceId: "2100", provinceName: "Kepulauan Riau" },
  { id: "6571", name: "Kota Tarakan", provinceId: "6500", provinceName: "Kalimantan Utara" },
  { id: "3278", name: "Kota Tasikmalaya", provinceId: "3200", provinceName: "Jawa Barat" },
  { id: "1274", name: "Kota Tebing Tinggi", provinceId: "1200", provinceName: "Sumatera Utara" },
  { id: "3376", name: "Kota Tegal", provinceId: "3300", provinceName: "Jawa Tengah" },
  { id: "8271", name: "Kota Ternate", provinceId: "8200", provinceName: "Maluku Utara" },
  { id: "8272", name: "Kota Tidore Kepulauan", provinceId: "8200", provinceName: "Maluku Utara" },
  { id: "7173", name: "Kota Tomohon", provinceId: "7100", provinceName: "Sulawesi Utara" },
  { id: "8172", name: "Kota Tual", provinceId: "8100", provinceName: "Maluku" },
  { id: "3471", name: "Kota Yogyakarta", provinceId: "3400", provinceName: "DI Yogyakarta" }
];
